appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IdnkuBylkXeskv6kbb53x10g/Xh3lsXPwulUkrs7tNQ4jeJCXNG1Uhth8zpm9nX2jZjBIwqi+jwEMqxWQfntNXSl7BFJf/1+WSwF5/vc1vtc8DC81GjHVdSuIdwdcrJh3hrdli93z1bVbkwxtgQX/a2A9xoWf6CFwdHPK/qq6ZVn8xDlzl/WJ93ziHCUIwduJmXFO1CGiMheW4VMwgZXLw126QB/GZ1seAY1fd0VWZWi8z6doBYflWUFGsD8fv5SKKwkPoGNKXbXmt4dMg0HvUyGjNcUGjcWf8t+s08+XGRZ9lOXnCb8NegdCzBjcy8mQDEQKdk4PY5HfJth/D0nnfawU28WideuCTY4Gk0ZVvd4tgKnzLED8SrpisS5yW4AR0fgWNCm1Rx9Oozz7mHz5MlyR8rHgQEzXc6gQniVDmhT5hpCAfS36CIqEuKl9ui2vZolBcU9D4uAQu3X7+u6Ai3M7JlUUq4FMxtt2sJRP2Rl944FHVrvxREclkn0ZtFT8qpA81RT0IP7Ebu6GTYqnCPOOwvDqYWTXe2KuYedZmvtYZqj27/9pnx/p0kztmDWwp2VPC/9PtjQe4luy3IZrpQA6uokqJIBBH9VEiX8+EM0fx+PuTJ6cLrvjl3AcT2G6kwZy+9I2VnYw+BZHnLw66EsDJ523XMkqeG3Z6Xz6mQ=
