travis:
  secure:
    BINSTAR_TOKEN: tu4xIYW+/e1LfikGNt6w8f4z6oLR/0Z+20DwOCblngcb/1ygUCyPDcIyEPnU2lwMrHVATGdHethnkkdwprkQBQyrv+6XGZnNTVElm7YFfSdZg0JiiuiwRebW/DhGJcZG3ePPgCG4TsMnJWD8+UxtmVakq68JZhjYpr3bx2U2GUH12vGtLRBTiN9du8THJlf4hgBazUIXLx0T3tREBQFyigA6c5N63WhK7NIp7SGKPhj6M5VxpxXIdDQdVPhQOyBBMjnbg8dYvh+/SqvwngOuJscK7d2/AeYqxdk+gQrf2W5n6Qg4pU462jfPZwNCwXm9oRTNRXM4GuNRDxFOIHARGFiiccBg/1Px+T4Gs3LntrLoqm4qufPv0b4lAQXGfpvRwsV1mOkvcgma2bSSOmXzt/EqJw+kCdW0rVUIso5sDhqWHFmZCKasyktCwIfS6iKXUVXJMg/5qElInNMnV/xfiMYBF56MBjvgLXmVUv4OR0D7VP1zihTc28fBrjg9+ERDtY4i02xqHmqjvhjzwlWgO1XfPIpeRj86yh73JCtyPP1WU24UQgjxql3Xne7DUTxEe3+HEiOQni5rhuHwcKF9fKkFXncuiQkBZhdQIQnFNALxp/rBBtojau2CNPbAQYvdlpsVXI3Niox502SL2nChkEJNYUjgSwSOvV4p/wkjsTc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
